"""
Delete automated Crewhu notes from ConnectWise tickets.

This script removes notes that were previously created by the
POST_Notes_Internal.py script. Useful for cleanup or re-running.
"""

import json
import requests
from pathlib import Path

from connectwise_api import (
    require_credentials,
    get_headers,
    ticket_notes_url
)

# ==========================================
# CONFIGURATION
# ==========================================
DRY_RUN = False  # Set to True to preview deletions without making them

INPUT_FILE = Path("crewhu_surveys_clean.json")


# ==========================================
# DELETE LOGIC
# ==========================================
def process_ticket_deletion(ticket_id, headers):
    """Find and delete automated Crewhu notes from a ticket."""
    notes_url = ticket_notes_url(ticket_id)

    try:
        # Get all notes for the ticket
        response = requests.get(notes_url, headers=headers)

        if response.status_code == 404:
            print(f"[{ticket_id}] Ticket not found.")
            return 0
        elif response.status_code != 200:
            print(f"[{ticket_id}] Error fetching notes: {response.status_code}")
            return 0

        notes = response.json()
        notes_deleted = 0

        # Loop through notes to find matches
        for note in notes:
            note_id = note.get('id')
            text = note.get('text', '')

            # Only delete if it matches the specific format generated by our scripts
            if "just gave a" in text and "Customer feedback:" in text:

                if DRY_RUN:
                    print(f"[{ticket_id}] (DRY RUN) Would delete Note ID {note_id}:")
                    print(f"    Content: {text[:50]}...")
                else:
                    del_url = ticket_notes_url(ticket_id, note_id)
                    del_resp = requests.delete(del_url, headers=headers)

                    if del_resp.status_code in [200, 204]:
                        print(f"[{ticket_id}] Deleted Note ID {note_id}")
                        notes_deleted += 1
                    else:
                        print(f"[{ticket_id}] Failed to delete Note {note_id}: {del_resp.status_code}")

        if notes_deleted == 0 and not DRY_RUN:
            print(f"[{ticket_id}] No matching Crewhu notes found.")

        return notes_deleted

    except Exception as e:
        print(f"[{ticket_id}] Connection error: {e}")
        return 0


# ==========================================
# MAIN
# ==========================================
def main():
    # Validate credentials
    require_credentials()

    if not INPUT_FILE.exists():
        print(f"ERROR: {INPUT_FILE} not found.")
        print("Make sure the JSON file is in the same folder.")
        return

    headers = get_headers()

    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)

    print(f"Starting cleanup for {len(data)} tickets")

    if DRY_RUN:
        print("!!! DRY RUN MODE - No data will be deleted !!!\n")

    total_deleted = 0

    for entry in data:
        ticket_id = entry.get('ticket_number')
        if ticket_id:
            deleted = process_ticket_deletion(ticket_id, headers)
            total_deleted += deleted

    # Summary
    print("\n" + "=" * 40)
    print("SUMMARY")
    print("=" * 40)
    print(f"Total tickets processed: {len(data)}")
    print(f"Total notes deleted:     {total_deleted}")

    if DRY_RUN:
        print("\nDRY RUN COMPLETE - Set DRY_RUN = False to perform deletions.")


if __name__ == "__main__":
    main()
